# Generated by Django 4.2.4 on 2023-09-22 14:22

from django.db import migrations, models
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_count', models.PositiveIntegerField(default=1)),
                ('bg', models.PositiveIntegerField(default=1)),
                ('photos', models.JSONField(decoder=json.decoder.JSONDecoder, default=list, encoder=json.encoder.JSONEncoder)),
                ('chromas', models.JSONField(decoder=json.decoder.JSONDecoder, default=list, encoder=json.encoder.JSONEncoder)),
                ('frame', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('START', 'Start Page'), ('BG', 'Background Select'), ('GUIDE', 'Guide before camera'), ('CAM', 'Camera'), ('FRAME', 'Frame Select'), ('LOAD', 'Final Loading'), ('END', 'End')], default='START', max_length=5)),
            ],
        ),
    ]
