# Generated by Django 4.2.4 on 2023-09-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_alter_cut_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='video_code',
            field=models.PositiveIntegerField(default=999999),
        ),
    ]
