# Generated by Django 4.2.4 on 2023-09-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='')),
                ('cnt', models.PositiveIntegerField()),
                ('code', models.PositiveIntegerField()),
            ],
        ),
    ]
